source 'https://rubygems.org'

ruby "2.3.3"

# Windows zone
gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

# Middleman Gems
gem 'middleman', '~> 4.1.0'
gem 'middleman-livereload'

# Custom gems
gem 'middleman-sprockets', github: 'middleman/middleman-sprockets', branch: 'master'
gem 'sass-globbing', '~> 1.1.1', require: false
gem 'gintonic-rails', github: 'simplelogica/gintonic-rails', branch: 'master'
