source 'https://rubygems.org'

ruby "2.3.3"

# Windows zone
gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

# Middleman Gems
gem 'middleman', '>= 4.0.0'
gem 'middleman-sprockets', github: 'middleman/middleman-sprockets', branch: 'master'
gem 'middleman-autoprefixer'
gem 'middleman-livereload'

# Assets Gems
gem 'dom_limpio'
gem 'mqbe'
